name: wiraraja
version: '0.11.6'
synopsis: Simple web app, just for learning purpose
description: The synopsis is not enough to describe
category: Web
author: >
  Syaiful Bahri <syaiful.bahri6@yahoo.com>
  Chandra <chandra.nuh34@yahoo.com>
maintainer: Syaiful Bahri <syaiful.bahri6@yahoo.com>
license: BSD3
extra-source-files:
  - README.md

dependencies:
  - auto-update
  - base >= 4.7 && < 5
  - bifunctors >= 4 && < 6
  - blaze-builder
  - blaze-html
  - bytestring
  - cereal >= 0.3
  - clientsession >= 0.9.1 && < 0.10
  - containers
  - cookie >= 0.4.2 && < 0.5
  - deepseq >= 1.3
  - deepseq-generics
  - exceptions >= 0.7 && < 0.9
  - http-types >= 0.7
  - lifted-base >= 0.2.3 && < 0.2.4
  - monad-control >= 1.0.0.0 && < 1.1
  - monad-logger >= 0.3 && < 0.4
  - mtl >= 2.1.0 && < 2.3.0
  - mwc-random
  - persistent >= 2.5
  - persistent-postgresql >= 2.5
  - persistent-template >= 2.5
  - random >= 1.0.0.2  && < 1.2
  - text
  - time >= 1.1.4
  - transformers >= 0.3.0 && < 0.6
  - transformers-base >= 0.4.0 && < 0.5
  - transformers-compat >= 0.3.0
  - wai == 3.*
  - wai-extra == 3.*
  - warp == 3.*

library:
  source-dirs: src
  ghc-options: -Wall -O2

executables:
  wiraraja:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall -O2 -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - wiraraja
      - optparse-applicative >= 0.13.0

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -Wall
    dependencies:
      - wiraraja
      - hspec == 2.*
      - QuickCheck
